apiVersion: v1
kind: Service
metadata:
    name: nginx-svc-np
spec:
    ports:
     - name: web
       nodePort: 30001
       port: 80 
     - name: multitool
       nodePort: 30002
       port: 8080
    selector:
       app: nginx
    type: NodePort