---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    privileged: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy