---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
      clickhouse_version: 19.11.10.54
      clickhouse_repo: "https://repo.yandex.ru/clickhouse/repo-archive/rpm/stable/x86_64/"
      clickhouse_repo_key: https://repo.yandex.ru/clickhouse/repo-archive/CLICKHOUSE-KEY.GPG
      clickhouse_listen_host_default:
        - "127.0.0.1"
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install Lighthouse
  tags: 
    - lh
  hosts: lighthouse
  pre_tasks:
    - name: Lighthouse | Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Lighhouse | Install epel-release repo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Lighhouse | Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Lighthouse | Apply nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
    - name: Lighthouse | Nginx add to boot
      become: true
      ansible.builtin.systemd:
        name: nginx.service
        enabled: true
  roles:
    - lighthouse-role
  post_tasks:
    - name: Lighthouse | Apply config
      become: true
      ansible.builtin.template:
        src: lighthouse_nginx.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: 0644
    - name: Lighthouse | Nginx restart
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted 


  
  
