---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
- name: Install Lighthouse
  tags:
    - lh
  hosts: lighthouse
  roles:
    - lighthouse-role

  
  
