apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-nfs-test
  namespace: lesson6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-vol-nfs-test
  template:
    metadata:
      labels:
        app: pv-vol-nfs-test
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: vol
          mountPath: /in
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: pvc-nfs
