apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-nfs
  namespace: lesson6
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

