node("linux"){
    stage("Git checkout"){
        git credentialsId: 'e9bccc69-aad5-46c9-9281-a4de40ad5eb7', url: 'git@github.com:gizadirov/example-playbook.git'
    }
    stage("Sample define secret_check"){
        def status = sh(returnStatus: true, script: 'sudo echo')
        if (status == 0) {
            secret_check=true
        }
    }
    stage("Run playbook"){
        if (secret_check){
            if (params.prod_run) {
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
            else
            {
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
            }
        }
        else{
            echo 'need more action'
        }
    }
}