apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT                                                                                                                                                                    
          value: "81"